version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
